### PR TITLE
Init frame work discuss

### PR DESCRIPTION
**Pull request by qhsong**
- Add log.sh
- Add comment for every function
- Follow google shell style https://google.github.io/styleguide/shell.xml
- Pass shellcheck here:https://github.com/koalaman/shellcheck

### CODE REVIEW

**Comment by linuxqiao** [comment]
I hope you can division this pull requests, it's too large. I'm not very easy to add comments to aim at specific code.

**Comment by qhsong** [comment]
ok, I will try this.
It certainly contain many details I made. I will try and divide it into several PR

**Comment by qhsong** [comment]
On the file changed tab, the top left have a option, your can choose diff from 1a7f13b to show diff. That's my really modify files.It maybe clear for you to review.

**Comment by qhsong** [comment]
@linuxqiao  I pull request to qhsong branch. At the time of create qhsong branch, It didn't create Makefile.

**Comment by linuxqiao** [comment]
OH, will try to merge pull request.

**Pull request merged**
